// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gytlsjhwutuhnzmqwbvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5dGxzamh3dXR1aG56bXF3YnZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NzQwNTQsImV4cCI6MjA2ODM1MDA1NH0.35d6-NGsQ3Z4aG82DH3A9DWJuY0M5m_78N8XumfoR80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});