// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gytlsjhwutuhnzmqwbvo.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5dGxzamh3dXR1aG56bXF3YnZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NzQwNTQsImV4cCI6MjA2ODM1MDA1NH0.35d6-NGsQ3Z4aG82DH3A9DWJuY0M5m_78N8XumfoR80";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    persistSession: true,
    storage: localStorage
  }
});